service: seventeentest

plugins:
  - serverless-apigw-binary
  - serverless-api-compression
  - serverless-associate-waf
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 10
  region: ap-south-1
  apiGateway:
    shouldStartNameWithService: true

package:
  excludeDevDependencies: true
  patterns:
    - "!./**"
    - "!node_modules/@vendia/**"
    - "node_modules/aws-serverless-express/**"
    - "node_modules/binary-case/**"
    - "node_modules/type-is/**"
    - "node_modules/media-typer/**"
    - "node_modules/mime-types/**"
    - "node_modules/mime-db/**"
    - "node_modules/@angular/ssr"
    - "node_modules/@codegenie/**"
    - "dist/**"
    - "lambda.js"

functions:
  api:
    # server:
    handler: lambda.handler
    events:
      - http: ANY /{proxy+}
      - http: ANY /

custom:
  apigwBinary:
    types:
      - "*/*"
  # resources:
  #   - ${file(resources.yml)}
